services:
  redis-instance:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ycsb_net
    container_name: redis-instance

  mongo-instance:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - ycsb_net
    container_name: mongo-instance

  orient-instance:
    image: orientdb:latest
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
    container_name: orient-instance

networks:
  ycsb_net: {}